version: '{build}'
image: Visual Studio 2019
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: ConfuserExTools.sln
  verbosity: normal
artifacts:
- path: bin\Release
  name: ConfuserExTools
	
